on:
  push:
    branches:
      - "**"
  pull_request:
name: build
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Shellcheck
        run: shellcheck after-effects
  ubuntu:
    needs: ["shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["bionic", "focal", "jammy"]
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Ubuntu ${{ matrix.release }}
        run: ./scripts/test --build --trace --distro ubuntu --release "${{ matrix.release }}"
  debian:
    needs: ["shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["buster", "bullseye"]
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Debian ${{ matrix.release }}
        run: ./scripts/test --build --trace --distro debian --release "${{ matrix.release }}"
  ubuntu-arm:
    needs: ["shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["bionic", "focal", "jammy"]
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # ratchet:docker/setup-qemu-action@v2
      - name: Test on ARM64 ${{ matrix.release }}
        run: ./scripts/test --build --trace --distro arm64v8/ubuntu --release "${{ matrix.release }}"
  # Debian ARM64
  debian-arm:
    needs: ["shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["buster", "bullseye"]
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # ratchet:docker/setup-qemu-action@v2
      - name: Test on ARM64 ${{ matrix.release }}
        run: ./scripts/test --build --trace --distro arm64v8/debian --release "${{ matrix.release }}"

  # release:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v3 # ratchet:exclude
  #       with:
  #         persist-credentials: true
  #         fetch-depth: 0
  #     - name: Get the version
  #       id: get_version
  #       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
  #     - name: Version
  #       run: echo $VERSION
  #     - name: Checksums
  #       run: sha256sum after-effects | cut -f 1 -d ' ' | tee after-effects.sha256
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # ratchet:actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ steps.get_version.outputs.VERSION }}
  #         release_name: Release ${{ steps.get_version.outputs.VERSION }}
  #         draft: false
  #         prerelease: false
  #     - name: Upload Script
  #       uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # ratchet:actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: after-effects
  #         asset_name: after-effects
  #         asset_content_type: text/plain
  #     - name: Upload Checksum SHA256
  #       uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # ratchet:actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ steps.create_release.outputs.upload_url }}
  #         asset_path: after-effects.sha256
  #         asset_name: after-effects.sha256
  #         asset_content_type: text/plain
