name: docs
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build Docs
        run: |
          ./scripts/build-docs
