name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # For creating releases
      contents: write
    steps:
      - uses: actions/checkout@v3 # ratchet:exclude
        with:
          persist-credentials: true
          # Avoid breaking git rev date plugin
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Version
        run: echo $VERSION
      - name: Checksums
        run: sha256sum after-effects | cut -f 1 -d ' ' | tee after-effects.sha256
      # create a release on tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # ratchet:actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      # Upload Release assets
      - name: Upload Script
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # ratchet:actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: after-effects
          asset_name: after-effects
          asset_content_type: text/plain
      - name: Upload Checksum SHA256
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # ratchet:actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: after-effects.sha256
          asset_name: after-effects.sha256
          asset_content_type: text/plain
